### ISSUE TITLE
TempSource groups

### ISSUE THREAD

**Issue by Th3M1k3y** [SasaKaranovic/OpenFanUnraidService#2]
Here I am again, and once again talking about groups. :)

In this scenario (which is how it is in my server) 4 drives are covered by 1 fan, but I only see the option to control that fan by the temperature from one sensor.

The drives in my server are sitting at standby for most of the day, so when one disk is needed it is started up it gets warmer than the other drives, which are returning *c because of being in standby.

My suggestion
```
        {
            "Name": "Top_drives",
            "TempSource": [
                "cache",
                "parity",
                "disk1",
                "disk2"
            ],
            "TempGroup": "high",
            "UsePWM": false,
            "Points": [
                "0,1000",
                "45,1200"
            ]
        }
```

So TempSource will specify all the sensors which needs to be checked. `TempGroup` can then be set to either `avg` or `high` (default/not specified). When set to `high`, the profile will return the highest measured temperature from the measured sensors, and if set to `avg` it returns the average of the temperatures.

Readings of *c are ignored when set to return `avg`, if all disks are in standby, 0c is returned as it is currently.

**Comment by SasaKaranovic** [comment]
Hello there again! :)

I like this idea!
It makes sense to allow user to specify multiple sensors and then set how they should be evaluated.

Maybe instead of average, it would be better to return median value since often average will not represent any single element of the array.
For example if you have two disks that are at 65C and another one that is at 20C, the average will be 50C where as median would be 65C which is more accurate. Or add support for all three options; `max`, `avg` and `median`.

**Comment by Th3M1k3y** [comment]
Yes, median would probably be a good idea to have in too.

**Comment by Th3M1k3y** [comment]
So I have been cooking on another extension of this, but I haven't been able to fully figure out how it would make sense or how it would be configured to make sense.

Right now in my server, all the fans are still connected to the mainboard, and there I got the option to turn the different fans on or off, based on temperature from a sensor. After turning the fan on, it is then possible to make it ramp up and down with a fan curve. I use that to help the cpu heatsink, or go up to 100% if the fan on the cpu would fail.

I am aware the openfancontroller can't turn the fans off, that is not what I am thinking about.

What I am thinking about, is how to have multiple temperature groups, and then be able to adjust how they should be used.

So one option could be `average`, where one group asks for 1000 rpm, and the other group asks for 2000 rpm, the set rpm would then be 1500 rpm.

Another option could be `high`, where if one asks for 1000 rpm, and the other 2000 rpm, the rpm would be set to 2000 rpm.


If cpu temperature then gets added to the service too, it would again be able to turn the fan up if cpu gets hot and increase flow through the case, instead of only basing it on harddrives.
