### ISSUE TITLE
Variable fan speed

### ISSUE THREAD

**Issue by Th3M1k3y** [SasaKaranovic/OpenFanUnraidService#3]
I have been testing a bit, where I set the target temperature of a hdd to 40c. When the temperature got over 40c it did as expected, and turned the fan speed up, and soon after it went below again, so the fan speed dropped down. However that was the cycle it would now continue, which became annoying, because the change of fan speed was noticeable.

This gave me yet another idea, if the Points could be both as they are now, but also a range where it would calculate the fan speed target.

For my corsair power supply I am using this to control the fan speed

```python
temperature = 25

temp_min = 20
temp_max = 30
fan_min = 500
fan_max = 1000
fan_duty = int((temperature-temp_min)*(fan_max-fan_min)/(temp_max-temp_min)+fan_min)
                                    
if fan_duty < fan_min:
    fan_duty = fan_min
if fan_duty > fan_max:
    fan_duty = fan_max
    
print(fan_duty)
```

With this I am calculating duty cycle of the fan, but using it to calculate rpm shouldn't be any different.

To not break already working config, it could be done something like this

```json
{
    "Name": "DefaultProfile",
    "TempSource": "parity",
    "UsePWM": false,
    "Points": [
        "0,500",
        "20,500-30,1000",
        "40,2000"
    ]
}
```
So from 0c it would set the target to 500rpm, and between 20c and 30c it would calculate the target rpm, with a max of 1000rpm.

In this example the target would then be 750 rpm at 25c.

From 30c and up to next point, it would continue at 1000rpm, just as it currently does. When reaching 40c it would then set the target to 2000rpm

**Comment by SasaKaranovic** [comment]
This is good idea and something I have on the to-do list but not exactly as you described it.
Currently it's not listed in the config but all the fan curves are of type `threshold`.
Basically as soon as the temperature crosses a threshold, that is the fan value.
I plan on adding `linear`  fan curve which would take into consideration the point below and the point above current temperature and based on those two points, interpolate what the RPM should be.

Basically if you have your points defined as
```
...
"Points": [
    "10,500",
    "20,1000",
    "30,1500",
    "40,2000"
]
...
```

A simple example using above fan curve points.
With `linear` fan curve, if the temperature is 35C;
The point below is 30C which asks for 1500 RPM.
The point above is 40C which ask for 2000 RPM.
The service will interpolate between those two values and set the fan to 1750.

If the temperature is 45C, it would set the fan to 2000 RPM because there is no above point.
Same if the HDD is off and the temperature is reported as 0C, there is no below point so the fan will be at 500 RPM.

**Comment by Th3M1k3y** [comment]
That would in most cases work too.

My idea with having the options to have both points and a linear fan curve was so it was possible to define a "panic state" so if the temperature got to ex. 50c it could call for 100000 rpm (or something to get fans to run at max speed)

**Comment by SasaKaranovic** [comment]
You would still have that option.
The first and last point in `Points` would essentially mean "Above/below this point, use this RPM".
No interpolation is happening for those points.

For example if you set the last point as `"50,2000"`, above 50C it would automatically set the fan to 2000 RPM.
Same if you set the first point as `"20,500"`, below 20C it would always set the fan to 500 RPM.

**Comment by Th3M1k3y** [comment]
But if I set a point to 20,500 and 50,2000 it would only calculate the rpm target between those two, and then keep it at 2000rpm?

I guess I could still make the panic thing though
```json
"Points": [
    "20,500",
    "40,2000",
    "49.9,2000",
    "50,6000"
]
```

**Comment by SasaKaranovic** [comment]
Do you know what kind of fan(s) you have?
Most common PC fans are usually in the 1500-2000 RPM range and usually "high-speed" are 3000.
Setting the RPM to 6000 will not cause the 2000 RPM fan to spin at 6000 RPM. It will run at the maximum RPM that fan manufacturer has designed it for.

**Comment by Th3M1k3y** [comment]
> It will run at the maximum RPM that fan manufacturer has designed it for.

That is exactly what I am aiming for. Setting the speed higher than what the fans can do should ensure 100% on PWM.

**Comment by SasaKaranovic** [comment]
@Th3M1k3y just pushed new version of the application where you can specify a `linear` fan curve.
It works exactly as we discussed above.

When you get a chance, please give it a try and let me know how it goes.
You can just recreate the docker container (remove existing one and delete image and then create a new one).

**Comment by Th3M1k3y** [comment]
Seems to work as expected. :)

```
            "UsePWM": false,
            "CurveType": "linear",
            "Points": [
                "0,900",
                "30,1000",
                "40,2000"
            ]
```

![image](https://github.com/SasaKaranovic/OpenFanUnraidService/assets/29869794/55b3fc42-da82-4e89-a277-245fdc0fb039)
